import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  AtSign,
  BarChart2,
  Bell,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  FileText,
  HelpCircle,
  Image,
  Info,
  Link,
  LogIn,
  LogOut,
  Mail,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Sparkles,
  Star,
  Trash2,
  User,
  UserPlus,
  Users,
  X,
  XCircle,
  Zap,
  ZapOff,
  type LucideIcon,
} from "lucide-react-native";
import React from "react";
import type { StyleProp, ViewStyle } from "react-native";

const ICON_MAP: Record<string, LucideIcon> = {
  "add":                       Plus,
  "alert-circle":              AlertCircle,
  "arrow-back":                ArrowLeft,
  "arrow-forward":             ArrowRight,
  "at-outline":                AtSign,
  "bulb-outline":              Sparkles,
  "calendar-outline":          Calendar,
  "chatbubble-outline":        MessageCircle,
  "chatbubbles":               MessageSquare,
  "checkmark":                 Check,
  "checkmark-circle":          CheckCircle,
  "checkmark-circle-outline":  CheckCircle,
  "checkmark-done":            CheckCheck,
  "chevron-down":              ChevronDown,
  "chevron-forward":           ChevronRight,
  "chevron-up":                ChevronUp,
  "close":                     X,
  "close-circle":              XCircle,
  "close-circle-outline":      XCircle,
  "copy-outline":              Copy,
  "document-text-outline":     FileText,
  "ellipsis-horizontal":       MoreHorizontal,
  "enter-outline":             LogIn,
  "exit-outline":              LogOut,
  "flash-off-outline":         ZapOff,
  "help-circle-outline":       HelpCircle,
  "image-outline":             Image,
  "information-circle-outline": Info,
  "link":                      Link,
  "log-out-outline":           LogOut,
  "mail":                      Mail,
  "mail-outline":              Mail,
  "notifications-outline":     Bell,
  "pencil-outline":            Pencil,
  "people":                    Users,
  "people-outline":            Users,
  "person-add-outline":        UserPlus,
  "person-outline":            User,
  "refresh-outline":           RefreshCw,
  "search-outline":            Search,
  "send":                      Send,
  "settings-outline":          Settings,
  "share-social-outline":      Share2,
  "shield-outline":            Shield,
  "sparkles":                  Sparkles,
  "sparkles-outline":          Sparkles,
  "star-outline":              Star,
  "stats-chart-outline":       BarChart2,
  "time-outline":              Clock,
  "trash-outline":             Trash2,
  "user":                      User,
  "users":                     Users,
  "x":                         X,
  "zap":                       Zap,
};

export type IconName = keyof typeof ICON_MAP;

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: StyleProp<ViewStyle>;
}

export function Icon({ name, size = 24, color = "#888", style }: IconProps) {
  const LucideComponent = ICON_MAP[name];
  if (!LucideComponent) return null;
  return <LucideComponent size={size} color={color} style={style as object} />;
}
